<?php
use Drupal\Core\Form;
use Drupal\user\Entity;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;




function article_form_alter(&$form, FormStateInterface $form_state, $form_id){

if($form_id == "node_page_form" || $form_id == "node_page_edit_form"){
 $form['field_city']['widget'][0]['value']['#default_value'] = 'avaneesh';



}
}
